name: Run Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run Docker Compose
        run: docker-compose build

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
